name: Auto_Push

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: jianliao/merge-gh-pages-branch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Echo Branch Name
      run: echo $GITHUB_REF !!!!!!! Again !!! Again!!!
    # - name: Git Merge Branch
    #   run: git merge origin/123_test_result --allow-unrelated-histories --no-edit
    # - name: Git Push gh-pages branch
    #   run: git push origin gh-pages
